export const ARMOR_BASES: Armor[] = [
  {
    id: 1,
    name: 'Archon Plate',
    defenseLow: 410,
    defenseHigh: 524,
    reqStr: 103,
    reqLvl: 63,
    qLvl: 84,
    tClass: 84,
    sockets: 4,
    weight: 'light',
    class: 'elite',
    image: 'lightplate.png',
    player: true,
    merc: true,
    eth: true
  },
  {
    id: 2,
    name: 'Mage Plate',
    defenseLow: 225,
    defenseHigh: 261,
    reqStr: 55,
    reqLvl: 25,
    qLvl: 60,
    tClass: 60,
    sockets: 3,
    weight: 'light',
    class: 'exceptional',
    image: 'lightplate.png',
    player: true,
    merc: false,
    eth: false
  },
  {
    id: 3,
    name: 'Dusk Shroud',
    defenseLow: 361,
    defenseHigh: 467,
    reqStr: 77,
    reqLvl: 49,
    qLvl: 65,
    tClass: 66,
    sockets: 4,
    weight: 'light',
    class: 'exceptional',
    image: 'quilted.png',
    player: true,
    merc: false,
    eth: false
  },
  {
    id: 4,
    name: 'Sacred Armor',
    defenseLow: 487,
    defenseHigh: 600,
    reqStr: 232,
    reqLvl: 66,
    qLvl: 85,
    tClass: 87,
    sockets: 4,
    weight: 'medium',
    class: 'elite',
    image: 'ancientarmor.png',
    player: false,
    merc: true,
    eth: true
  },
  {
    id: 5,
    name: 'Wyrmhide',
    defenseLow: 364,
    defenseHigh: 470,
    reqStr: 84,
    reqLvl: 50,
    qLvl: 67,
    tClass: 60,
    sockets: 4,
    weight: 'light',
    class: 'elite',
    image: 'leather.png',
    player: true,
    merc: false,
    eth: false
  },
  {
    id: 6,
    name: 'Scarab Husk',
    defenseLow: 369,
    defenseHigh: 474,
    reqStr: 95,
    reqLvl: 51,
    qLvl: 68,
    tClass: 69,
    sockets: 4,
    weight: 'light',
    class: 'elite',
    image: 'hardleather.png',
    player: true,
    merc: false,
    eth: false
  },
  {
    id: 7,
    name: 'Wire Fleece',
    defenseLow: 375,
    defenseHigh: 481,
    reqStr: 111,
    reqLvl: 53,
    qLvl: 70,
    tClass: 72,
    sockets: 4,
    weight: 'light',
    class: 'elite',
    image: 'studdedleather.png',
    player: true,
    merc: false,
    eth: false
  },
  {
    id: 8,
    name: 'Great Hauberk',
    defenseLow: 395,
    defenseHigh: 501,
    reqStr: 118,
    reqLvl: 56,
    qLvl: 75,
    tClass: 75,
    sockets: 4,
    weight: 'light',
    class: 'elite',
    image: 'breastplate.png',
    player: true,
    merc: false,
    eth: false
  },
  {
    id: 9,
    name: 'Kraken Shell',
    defenseLow: 417,
    defenseHigh: 523,
    reqStr: 174,
    reqLvl: 61,
    qLvl: 81,
    tClass: 81,
    sockets: 4,
    weight: 'medium',
    class: 'elite',
    image: 'fieldplate.png',
    player: false,
    merc: true,
    eth: true
  },
  {
    id: 10,
    name: 'Hellforge Plate',
    defenseLow: 421,
    defenseHigh: 530,
    reqStr: 196,
    reqLvl: 59,
    qLvl: 78,
    tClass: 78,
    sockets: 4,
    weight: 'heavy',
    class: 'elite',
    image: 'platemail.png',
    player: false,
    merc: true,
    eth: true
  },
  {
    id: 11,
    name: 'Lacquered Plate',
    defenseLow: 433,
    defenseHigh: 541,
    reqStr: 208,
    reqLvl: 62,
    qLvl: 82,
    tClass: 84,
    sockets: 4,
    weight: 'medium',
    class: 'elite',
    image: 'gothicplate.png',
    player: false,
    merc: true,
    eth: true
  },
  {
    id: 12,
    name: 'Shadow Plate',
    defenseLow: 446,
    defenseHigh: 557,
    reqStr: 230,
    reqLvl: 64,
    qLvl: 83,
    tClass: 84,
    sockets: 4,
    weight: 'heavy',
    class: 'elite',
    image: 'fullplate.png',
    player: false,
    merc: true,
    eth: true
  }
] as const
